### ISSUE TITLE
couldn't import postman collection json file

### ISSUE THREAD

**Issue by pj4316** [EsperoTech/yaade#43]
i have two questions about `postman collection import`.
- collection multi depth
- collection variables

1. `depth`.
If i have a collection that has multi depth like directory, then `import operation` must occur 500 error.
postman's collection supports multi depth (like directory), but yaade's collection only supports 1 depth.
when I flatten this collection, then I could import this.

i suggest multi depth of collection.

2. `variables`
if i want to use a variable of environment in postman, the format is `{{VARIABLE_NAME}}`.
but the format in yaade is `${VARIABLE_NAME}`.
after i import the postman collection, i should find the variables and replace `{{xxx}}` to `${xxx}`. that is not compitible I think.

I suggest `variable parser` when postman import.

**Comment by jonrosner** [comment]
1. yes nested collections are not yet supported. This is planned though. Once it will be supported by Yaade we will add it to the postman parser
2. True, variables are currently not parsed correctly if they are in the URL. It only works in the body and header. Will be fixed in next release. Thank you for pointing this out.
